spring:
  mail:
    host: smtp.gmail.com
    port: 25
    username: feb11vipin@gmail.com
    password: htvr cgia ocjh frsw
    properties:
      mail:
        smtp:
          auth: true
          startlts:
            enable: true